# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
plugins: [jekyll-paginate]
permalink:        pretty

# Setup
title:            Eun Jung YEO
#tagline:          'A Jekyll theme'
description:      'PhD candidate, Department of Linguistics, SNU'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Eun Jung YEO'
  url:            'https://eunjung31.github.io'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/eunjung31
