# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
plugins: [jekyll-paginate]
permalink:        pretty

# Setup
title:            Welcome!
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Eun Jung YEO'
  url:            'https://eunjung31.github.io'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
